[package]
name = "chat"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.10.0"
futures-lite = "2.5.0"
tokio = { version = "1.42.0", features = ["sync"] }
tungstenite = "0.24.0"
serde = { version = "1.0.216", features = ["rc", "derive"] }
serde_json = "1"